name: Build .NET 8 Windows Application

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore RoadcraftStutterRemover.csproj
      
    - name: Build application
      run: dotnet build RoadcraftStutterRemover.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test RoadcraftStutterRemover.csproj --no-build --verbosity normal --configuration Release
      continue-on-error: true
      
    - name: Publish application
      run: dotnet publish RoadcraftStutterRemover.csproj --configuration Release --output ./publish --no-build
      
    - name: Create zip archive
      run: Compress-Archive -Path ./publish/* -DestinationPath ./RoadcraftStutterRemover-${{ github.sha }}.zip
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-${{ github.sha }}
        path: ./RoadcraftStutterRemover-${{ github.sha }}.zip
        retention-days: 30
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}-${{ github.sha }}
        name: Build #${{ github.run_number }} (${{ github.sha }})
        prerelease: true
        generate_release_notes: true
        files: ./RoadcraftStutterRemover-${{ github.sha }}.zip
        body: |
          Automated build from commit ${{ github.sha }}
          
          Branch: ${{ github.ref_name }}
          Commit: ${{ github.event.head_commit.message }}
